---
title: "Mammal Sleep Behavior"
author: "Joselyn Angeles and Pippa Gallagher"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: yeti
    df_print: paged
    code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, echo=FALSE, include=FALSE}
library(tidyverse)
library(gt)
library(plotly)
library(patchwork)
sleep<-read.csv("SleepInMammals.csv")
```

## Introduction

```{r, echo=FALSE}
sleep %>% 
  select(!Gestation.time..days.:Overall.danger.index) %>% 
  arrange(desc(Body.Weight..kg.)) %>% 
gt(rowname_col = "row",
   groupname_col = "group") %>% 
  tab_header(
    title = md("**Sleep Patterns in Mammals**")) %>% 
  tab_footnote(
    footnote = "Weight in kilograms", 
    locations = cells_column_labels(
      columns = 2)) %>% 
  tab_footnote(
    footnote = "Weight in grams",
    locations = cells_column_labels(
      columns = 3)) %>%
  tab_footnote(
    footnote = "Non-dreaming hours per day",
    locations = cells_column_labels(
      columns = 4)) %>%
  tab_footnote(
    footnote = "Dreaming hours per day",
    locations = cells_column_labels(
      columns = 5)) %>% 
  cols_label(
    Species.of.animal="Species",
    Body.Weight..kg.="Body Weight",
    Brain.Weight..g. ="Brain Weight",
    Slow.wave.sleep..hrs.day. = "Slow Wave Sleep",
    Paradoxical.sleep..hrs.day. = "Paradoxical Sleep",
    Total.sleep..hrs.day.	= "Total Sleep",
    Maximum.life.span..years. ="Maximum Life Span (yrs)")
```

```{r, echo=FALSE}
sleep_graph<-
  sleep %>% 
  mutate(body_wtlbs = Body.Weight..kg.*2.20462) %>%  
  arrange(desc(body_wtlbs)) %>% 
  ggplot(aes(
    y = body_wtlbs, 
    x = Slow.wave.sleep..hrs.day.,
    size = body_wtlbs,
    alpha = .5,
    color= Species.of.animal))+
  geom_point() +
  labs(title = "Slow-wave sleep and body size (lbs)",
       x = "",
       y = "") +
  theme(plot.title.position = "plot",
        legend.position = "None") 

ggplotly(sleep_graph) %>% 
  hide_legend()
```

```{r, echo=FALSE}
sleep %>% 
    ggplot(aes(x = Overall.danger.index,
               y = fct_reorder(Species.of.animal,
                               Overall.danger.index,
                               .desc = FALSE),
               fill = Predation.index),
           color = "white") +
    geom_col() +
    labs(title = "Overall danger index of attacks from other animals for mammals",
         subtitle = "    ",
         caption = "Pippa Gallagher and Joselyn Angeles",
         x = "",
         y = "",
         fill = "Predation Index") +
  scale_x_continuous(expand = c(0,0)) +
    theme(
          axis.text.y = element_text(size = 6.5),
          plot.title.position = "plot",
          plot.caption.position = "plot",
          plot.title = element_text(color = "#0a203b"),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.major.y = element_blank(),
          panel.grid.minor.y = element_blank(),
          panel.background = element_rect(color = "white"),
          plot.background = element_rect(color = "white")) +
    scale_fill_gradient(high = "#0a203b", low = "#c3deff")
```

```{r, echo=FALSE}
G0 <-
sleep %>% 
  mutate(percent_dreaming = (Paradoxical.sleep..hrs.day./Total.sleep..hrs.day.) * 100) %>% 
  filter(percent_dreaming != 0) %>% 
  ggplot() +
  geom_col(aes(x = percent_dreaming, 
               y = fct_reorder(Species.of.animal, percent_dreaming, median),
               fill = Total.sleep..hrs.day.)) +
  labs(title = "How Much do Mammals Dream",
       y = "",
       x = "Percentage of Hours Dreaming",
       fill = "Total Sleeping Hours",
       caption = "Pippa Gallagher and Joselyn Angeles",
       subtitle = "    ") +
  theme(
    axis.text.y = element_text(size = 6.5),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    plot.title.position = "plot",
    plot.title = element_text(color = "#0a203b"),
    plot.caption.position = "plot"
  ) +
  scale_x_continuous(expand = c(0,0)) +
  scale_fill_gradient(high = "#0a203b", low = "#c3deff")
G0

```

```{r, echo=FALSE}
G1 <-
  sleep %>% 
  filter(Species.of.animal %in% c("Horse", "Cow", "Pig", "Human", "Sheep", "Chimpanzee", "Goat", "Baboon", "Red fox", "Cat", "Rabbit", "Rat", "Ground squirrel", "Mouse")) %>% 
  select(Species.of.animal, Slow.wave.sleep..hrs.day.,Sleep.exposure.index) %>% 
  ggplot() +
  geom_col(aes(y = Slow.wave.sleep..hrs.day., 
               x = fct_reorder(Species.of.animal,Slow.wave.sleep..hrs.day.,median),
               fill = Sleep.exposure.index)) +
  geom_text(aes(y = Slow.wave.sleep..hrs.day. + 5, x=fct_reorder(Species.of.animal,Slow.wave.sleep..hrs.day.,median), label= Species.of.animal), color="white", fontface="bold",alpha=0.6, size= 2.5, inherit.aes = FALSE ) +
  scale_color_viridis_c(option = "magma") +
  labs(title = "Non-Dreaming Hours of Sleep per Day",
       caption = "Pippa Gallagher and Joselyn Angeles",
       subtitle = "This measures the number of hours of slow wave (non-dreaming) sleep each mammal, on avergae, has each night.\nThe Sleep Measure Index determines how vulnerable the mammal is when sleeping, with 1 being the least vulnerbale \nand 5 the most.",
       y = "",
       x = "",
       fill = "Sleep Exposure Index") +
  coord_polar(start = 0) +
  ylim(-3,18) +
   theme(
    axis.text.x = element_blank(),
    panel.grid = element_blank(),
    plot.background = element_rect(fill = "#0a203b"),
    panel.background = element_rect(fill = "#0a203b"),
    legend.background = element_rect(fill = "#0a203b"),
    plot.title = element_text(color = "white"),
    plot.title.position = "plot",
    legend.text = element_text(color = "white"),
    legend.title = element_text(color = "white"),
    axis.text.y = element_text(color = "white"),
    plot.caption = element_text(color = "white"),
     plot.caption.position = "plot",
    plot.subtitle = element_text(color = "white", size = 7)) +
  scale_fill_gradient(high = "#2473db", low = "#c3deff")
  
G1
```


```{r, echo=FALSE}
G2 <-
  sleep %>% 
  filter(Species.of.animal %in% c("Horse", "Cow", "Pig", "Human", "Sheep", "Chimpanzee", "Goat", "Baboon", "Red fox", "Cat", "Rabbit", "Rat", "Ground squirrel", "Mouse")) %>% 
  select(Species.of.animal,Paradoxical.sleep..hrs.day. ,Sleep.exposure.index) %>% 
  ggplot() +
  geom_col(aes(y = Paradoxical.sleep..hrs.day., 
               x = fct_reorder(Species.of.animal,Paradoxical.sleep..hrs.day.,median),
               fill = Sleep.exposure.index)) +
  geom_text(aes(y = Paradoxical.sleep..hrs.day. + 2, x=fct_reorder(Species.of.animal,Paradoxical.sleep..hrs.day.,median), label= Species.of.animal), color="white", fontface="bold",alpha=0.6, size=2.5, inherit.aes = FALSE ) +
  labs(title = "Dreaming Hours of Sleep per Day",
       caption = "Pippa Gallagher and Joselyn Angeles",
       subtitle = "This measures the number of hours of paradoxical (dreaming) sleep each mammal, on avergae, has each night.\nThe Sleep Measure Index determines how vulnerable the mammal is when sleeping, with 1 being the least vulnerbale\nand 5 the most.",
       y = "",
       x = "",
       fill = "Sleep Exposure Index") +
  coord_polar(start = 0) +
  ylim(-1.5,6) +
     theme(
    axis.text.x = element_blank(),
    panel.grid = element_blank(),
    plot.background = element_rect(fill = "#0a203b"),
    panel.background = element_rect(fill = "#0a203b"),
    legend.background = element_rect(fill = "#0a203b"),
    plot.title = element_text(color = "white"),
    plot.title.position = "plot",
    legend.text = element_text(color = "white"),
    legend.title = element_text(color = "white"),
    axis.text.y = element_text(color = "white"),
    plot.caption = element_text(color = "white"),
    plot.caption.position = "plot",
    plot.subtitle = element_text(color = "white", size = 7)) +
  scale_fill_gradient(high = "#2473db", low = "#c3deff")
G2

```


```{r, echo=FALSE}
G3 <-
  sleep %>% 
  ggplot() +
  geom_violin(aes(x = Overall.danger.index,
                  y = Maximum.life.span..years.),
                  color = "#2473db",
                  fill = "#c3deff") +
  theme(
    plot.background = element_rect("#0a203b"),
    panel.background = element_rect("#0a203b"),
    plot.title = element_text(color = "white"),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    axis.text = element_text(color = "white"),
    plot.caption = element_text(color = "white"),
    plot.caption.position = "plot",
    plot.title.position = "plot",
    plot.subtitle = element_text(color = "white", size = 7)
  ) +
  labs(x = "",
       y = "",
       title = "The Correlation between Maximum Life Span and Danger Index",
       subtitle = "The Danger Index determines how vulnerable the mammal is to harm, with 1 being the least vulnerbale and 5 the most.",
       caption = "Pippa Gallagher and Joselyn Angeles")
  
G3
```

```{r, echo=FALSE}
G4 <-
  sleep %>% 
   filter(Species.of.animal %in% c("Horse", "Cow", "Pig", "Human", "Sheep", "Chimpanzee", "Goat", "Baboon", "Red fox", "Cat", "Rabbit", "Rat", "Ground squirrel", "Mouse")) %>% 
  mutate(Total_hours_sleeping_life = Total.sleep..hrs.day. * (Maximum.life.span..years. * 365),
         Total_hours_alive = Maximum.life.span..years. * 365 * 24,
         Prop_spent_sleeping = (Total_hours_sleeping_life/Total_hours_alive) *100) %>% 
   ggplot() +
  geom_col(aes(y = Prop_spent_sleeping, 
               x = fct_reorder(Species.of.animal,Prop_spent_sleeping,median),
              fill = Maximum.life.span..years.)) +
  geom_text(aes(y = Prop_spent_sleeping + 20, x=fct_reorder(Species.of.animal,Prop_spent_sleeping,median), label= Species.of.animal), color="white", fontface="bold",alpha=0.6, size=2.5, inherit.aes = FALSE ) +
  coord_polar(start = 0) +
  ylim(-5,90) +
   theme(
    axis.text.x = element_blank(),
    panel.grid = element_blank(),
    plot.background = element_rect(fill = "#0a203b"),
    panel.background = element_rect(fill = "#0a203b"),
    legend.background = element_rect(fill = "#0a203b"),
    plot.title = element_text(color = "white"),
    plot.title.position = "plot",
    legend.text = element_text(color = "white"),
    legend.title = element_text(color = "white"),
    axis.text.y = element_text(color = "white"),
    plot.caption = element_text(color = "white"),
    plot.caption.position = "plot",
    plot.subtitle = element_text(color = "white", size = 7)) +
  scale_fill_gradient(high = "#2473db", low = "#c3deff") +
  labs(title = "Proportion of Mammals' Lives Spent Sleeping",
       x = "",
       y = "",
       caption = "Pippa Gallagher and Joselyn Angeles",
       fill = "Maximum Life Span")
  
G4 
```

```{r, echo=FALSE}
G5 <-
sleep %>% 
  pivot_longer(cols = Slow.wave.sleep..hrs.day.:Paradoxical.sleep..hrs.day., names_to = "Dream_Type", values_to = "Hours") %>% 
  ggplot() +
  geom_col(aes(x = Hours, y = fct_reorder(Species.of.animal, Hours), fill = Dream_Type)) +
  labs(title = "Proportion of Dreaming vs Non-Dreaming Sleep",
       y = "",
       x = "",
       fill = "Sleep Type",
       caption = "Pippa Gallagher and Joselyn Angeles",
       subtitle = "    ") +
  theme(
    axis.text.y = element_text(size = 6.5),
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y = element_blank(),
    panel.grid.minor.y = element_blank(),
    plot.title.position = "plot",
    plot.title = element_text(color = "#0a203b"),
    plot.caption.position = "plot"
  ) +
  scale_x_continuous(expand = c(0,0)) +
  scale_fill_manual(labels = c("Dreaming", "Non-Dreaming"), values = c("#0a203b","#2473db"))

G5  
```





